model:
  name: "sgda_net"
  args:
    num_classes: 19

dataset:
  type: "standard"
  image_size: 512

training:
  epochs: 100
  batch_size: 4
  weight_decay: 0.01
  loss_lr: 1e-4
  optim_groups:
    - attr: "segformer.segformer"
      lr: 6e-5
    - attr: "segformer.decode_head"
      lr: 1e-4
    - attr: "depth_feat"
      lr: 1e-4
    - attr: "cross_attention"
      lr: 1e-4
    - attr: "depth_out"
      lr: 1e-4

testing:
  batch_size: 4

loss:
  type: "uncertainty"